apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: retro-store
  name: retro-store-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retro-store
  template:
    metadata:
      labels:
        app: retro-store
      name: retro-store
    spec:
      containers:
        - name: web
          image: dtr.us.demo.mirantis.com/dkramer-dev/retro-store:2020.06.23.4945fc4
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: retro-store-service
  labels:
    name: retro-store-service
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: retro-store
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: retro-store
spec:
  hosts:
    - retro-store.launch.kube.webinar.mirantis-demos.mirantis.com
  gateways:
    - istio-system/demo-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: retro-store-service
            port:
              number: 80

  